source 'http://rubygems.org'

gem 'rails', '2.3.5'
gem 'warden'
gem 'devise'
gem 'will_paginate', '~> 2.0'
gem 'settingslogic'                                                             
gem 'fastercsv'                                                                 
gem 'rest-client'                                                               
gem 'mechanize'                                                                 
gem 'json', '1.5.0'
gem 'rake',  '0.8.7'
gem 'mysql2', '< 0.3'
