source 'https://rubygems.org'

gem 'rails', '2.3.5'
gem 'mysql', '2.9.0'
gem 'warden','0.10.7'
gem 'devise', '1.0.11'
gem 'will_paginate', '~> 2.0'
gem 'settingslogic'                                                             
gem 'fastercsv'                                                                 
gem 'rest-client'                                                               
gem 'mechanize'                                                                 
gem 'json', '1.5.0'
gem 'rake', '0.8.7'
gem 'rcov'
gem 'passenger','4.0.38'
