# production:
#   adapter: mysql
#   database: openmrs
#   username: root
#   password:
#   host: localhost

development:
  adapter: mysql
  database: test
  username: root #root
  pool: 30
  password: letusout
  host: localhost

test: &TEST
  adapter: mysql
  database: bart2_test
  username: root
  password: password
  host: localhost

cucumber:
  <<: *TEST

migration:
  adapter: mysql
  database: test
  username: root
  password: password
  host: localhost

