production:
   adapter: mysql
   database: openmrs
   username: root
   password:
   host: localhost

development:
  adapter:  mysql
  database: bart2_development
  username: root
  password: root
  host: localhost
  pool: 500

test: &TEST
  adapter: mysql
  database: bart2_test
  username: root
  password: root
  host: localhost

cucumber:
  <<: *TEST
