# production:
#   adapter: mysql
#   database: openmrs
#   username: root
#   password:
#   host: localhost

development:
  adapter: mysql
  database: openmrs_dmht
  username: meduser #root
  pool: 30
  password: root
  host: 192.168.11.26

test: &TEST
  adapter: mysql
  database: bart2_test
  username: root
  password: password
  host: localhost

cucumber:
  <<: *TEST

migration:
  adapter: mysql
  database: test
  username: root
  password: password
  host: localhost

