#!/usr/bin/env ruby

# script/load_words "{\"field1\":\"value1\",\"field2\":\"value2\"}" tu

require File.expand_path('../../config/environment.rb',  __FILE__)

if !(ARGV[0]).to_s.match(/^\{.+\}$/)

  puts "\n\tUSAGE:"
  
  print "\t\t"
  
  puts 'script/load_words "{\"field1\":\"value1\",\"field2\":\"value2\"}" [target locale code e.g. \'ny\' for Chichewa]'
  
  puts ""
  
else

  target_locale = ARGV[1] rescue "ny"

  target_locale = "ny" if target_locale.blank?

  JSON.parse(ARGV[0]).each do |k, v|
    puts "#{k} => #{v}"
    
    id = Vocabulary.find_or_create_by_value(:value => k).id rescue nil
    
    Word.find_or_create_by_vocabulary_id_and_locale_and_value(
      :vocabulary_id => id, 
      :locale => "en", 
      :value => k) if !id.nil?
    
    Word.find_or_create_by_vocabulary_id_and_locale_and_value(
      :vocabulary_id => id, 
      :locale => target_locale, 
      :value => v) if !id.nil?
    
    File.open('db/data/vocabulary.json', 'w') {|f| f << Vocabulary.all.to_json} 
    
    File.open('db/data/word.json', 'w') {|f| f << Word.all.to_json}

  end rescue nil

end


